### ISSUE TITLE
Cannot install Not For Profir Accelerator

### ISSUE THREAD

**Issue by rksharma24** [microsoft/Dynamics-365-Industry-Accelerators#32]
**Describe the bug**
I’m trying to install the ‘Microsoft Dynamics 365 Nonprofit Accelerator’ but it does not seem to install anything.
It switches to the Solutions are of the admin portal but nothing else happens.
Are there any specific pre-requisites?

**To Reproduce**
1. Install app from Appsource

**Additional context**
Tried sending email to ''dynindaccsupport@microsoft.com" but it bounces back.

**Comment by mgernaey** [comment]
Hello rksharma24,

Unfortunately without seeing what you are seeing it is hard to say, but you will need a full CDS instance(Dynamics). You do not need PSA/FS though, so make sure marketing, sales, service are installed and working properly and enabled. Sometimes they aren't actually enabled.


Also I am looking into the issue with it bouncing back and apologize for the inconvenience, something happened recently as it was working fine.

**Comment by mgernaey** [comment]
FYI rksharma24, the email alias issue has been resolved, apologies

**Comment by CrazyShades91** [comment]
I am also having this issue.

Was there a resolution?

**Comment by rksharma24** [comment]
Yes, I installed it from GitHub.
