### ISSUE TITLE
Installing App from AppSource does not load Sample Data

### ISSUE THREAD

**Issue by MDoddio** [microsoft/Dynamics-365-Industry-Accelerators#35]
**Describe the bug**
Installing the Non-Profit App from AppSource does not install Sample Data
**To Reproduce**
1. Go to 'AppSource'
2. Click on 'Trial'
3. Follow wizard steps to initiate the install
4. Refresh Dynamics 365 Instance.
5. Go to Non-Profit App in the App Switcher
6. Open any view from the site map.
7. No data is installed

No error message is given. I can load the data by downloading the package installer, unzipping, then using the Data Migration Wizard load in the DefaultData.zip file.

**Expected behavior**
Sample data is loaded when the App is installed

**Comment by mgernaey** [comment]
HI MDoddio

This is actually by design we don't include the sample data at the same time. There are several reasons for this, as we also do this with our other (non accelerator) patterns as well. Health / Education etc will all be done this way. 

Thanks!
